FROM runpod/stable-diffusion:web-ui-12.0.0



# add our relauner.py and webui-user.sh
COPY web-ui/relauncher.py /web-ui/stable-diffusion-webui/relauncher.py
COPY web-ui/webui-user.sh /web-ui/stable-diffusion-webui/webui-user.sh

# add our custom start scripts.sh
COPY /web-ui/pre_start.sh /pre_start.sh

# add our stop.sh script
COPY stop.sh /stop.sh
