name: Publish docker images

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push docker images to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push ${{ github.repository }}:comfyui
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: comfy-ui/Dockerfile
          tags: ${{ github.repository }}:comfyui

      - name: Build and push ${{ github.repository }}:automatic1111
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: comfy-ui/Dockerfile
          tags: ${{ github.repository }}:automatic1111

      - name: Build and push ${{ github.repository }}:combined
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: comfy-ui/Dockerfile
          tags: ${{ github.repository }}:combined
